workflows:
  android-debug-workflow:
    name: ASD TechCreation Admin - Debug Build
    max_build_duration: 60
    instance_type: linux_x2

    environment:
      java: 17
      vars:
        PACKAGE_NAME: "com.ecommerce.asdtechcreationadmin"

    scripts:
      - name: Set execute permission for gradlew
        script: |
          chmod +x ./gradlew

      - name: Build debug APK
        script: |
          ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - karthikeyan25082000@gmail.com
        notify:
          success: true
          failure: true